# Learning Concepts(input , print)
print("Welcome to Band Name Genertaor 😎")
city=input("Enter Your City Name \n")
animal=input("Enter Your Pet's Name or a Name you Like \n")
print(f"Thank You for using Brand Generator Your Band Name is \n {city} {animal}")